import { defineFieldIds } from "./defineTemplate.js";

export const TALK_FIELDS = defineFieldIds({
  name: "basic.姓名",
  gender: "basic.性别",
  ethnicity: "basic.民族",
  nativePlace: "basic.籍贯",
  organizationOrClass: "basic.班级",
  studentId: "basic.学号",
  leagueJoinYearMonth: "basic.入团年月",
  idNumber: "basic.身份证号",
  applicationDate: "submit.入党申请书落款日期",
  formerPosition: "talk.曾任职务",
  partyBranch: "talk.入党谈话时所属党支部",
  interviewDate: "talk.申请人谈话日期",
  interviewRecord: "talk.谈话记录（收到入党申请书后一个月完成）",
});

const activistQuarter = (prefix, numeral) => ({
  report: `${prefix}.积极分子期间思想汇报电子版（${numeral}）`,
  reportDate: `${prefix}.电子版（${numeral}）落款日期`,
  startMonth: `${prefix}.电子版（${numeral}）所在季度起始月份`,
  endMonth: `${prefix}.电子版（${numeral}）所在季度截止月份`,
  opinion: `${prefix}.联系人意见（${numeral}）`,
  opinionDate: `${prefix}.联系人意见（${numeral}）落款日期`,
});

export const ACTIVIST_FIELDS = defineFieldIds({
  person: {
    name: "basic.姓名",
    organizationOrClass: "basic.班级",
    gender: "basic.性别",
    birthYearMonth: "basic.出生年月",
    idNumber: "basic.身份证号",
    phone: "basic.电话",
    studentId: "basic.学号",
    leagueJoinYearMonth: "basic.入团年月",
    applicationDate: "submit.入党申请书落款日期",
    currentPosition: "acknowledge.现任职务",
    initialBranchOpinion:
      "acknowledge.支委会(党员大会)对确定入党积极分子的意见",
    activistDate: "acknowledge.确定积极分子日期",
    partyBranch: "activist.确定积极分子时所在党支部",
    contact1: "activist.入党联系人1",
    contact1ProbationaryDate: "activist.入党联系人1入党时间（预备时间）",
    contact1FormalDate: "activist.入党联系人1转正时间",
    contact1Position: "activist.入党联系人1党内职务",
    contact2: "activist.入党联系人2",
    contact2ProbationaryDate: "activist.入党联系人2入党时间（预备时间）",
    contact2FormalDate: "activist.入党联系人2转正时间",
    contact2Position: "activist.入党联系人2党内职务",
    committeeRecordDate: "activist.积极分子党委备案日期",
    remark: "activist.备注",
  },
  quarters: [
    activistQuarter("season1_1", "一"),
    activistQuarter("season1_2", "二"),
    activistQuarter("season1_3", "三"),
    activistQuarter("season1_4", "四"),
  ],
  branchHalfYear: {
    opinion: "season1_half.党支部意见（半年）",
    date: "season1_half.党支部意见（半年）落款日期",
  },
  branchAnnual: {
    opinion: "season1_annual.党支部意见（一年）",
    date: "season1_annual.党支部意见（一年）落款日期",
  },
  candidate: {
    massOpinionDate: "candidate.发展对象群众座谈会日期",
    branchCommitteeOpinion: "candidate.支委会（党员大会意见）",
    branchCommitteeDate: "candidate.支委会日期",
    deputySecretaryDate: "candidate.学工副书记（负责人）意见日期",
    committeeRecordDate: "candidate.党委备案日期（确定发展对象日期）",
    publicityStartDate: "candidate.发展对象公示起始日期",
    publicityEndDate: "candidate.发展对象公示结束日期",
    branchReviewOpinion: "candidate.党支部审查意见",
    branchReviewDate: "candidate.党支部审查意见日期",
    committeePreReviewDate: "candidate.党委预审意见日期",
    partyBranch: "candidate.确定发展对象时支部名称",
    trainingClassName: "candidate.教育培训情况-培训班名称",
    trainingCompletionDate: "candidate.教育培训情况-结业日期",
    trainingSummary: "candidate.培训情况",
    politicalReviewDate: "candidate.政治审查报告日期",
  },
  wishBookNumber: "wish.志愿书编号",
});

const probationaryQuarter = (prefix, numeral) => ({
  startMonth: `${prefix}.电子版（${numeral}）所在季度起始月份`,
  endMonth: `${prefix}.电子版（${numeral}）所在季度截止月份`,
  opinion: `${prefix}.考察人意见（${numeral}）`,
  opinionDate: `${prefix}.考察人意见（${numeral}）落款日期`,
});

export const PROBATIONARY_FIELDS = defineFieldIds({
  personName: "basic.姓名",
  organizationOrClass: "basic.班级",
  probationaryPartyBranch: "probationary.预备党员时所在党支部",
  gender: "basic.性别",
  birthYearMonth: "basic.出生年月",
  nativePlace: "basic.籍贯",
  educationLevel: "probationary.文化程度",
  currentPosition: "probationary.预备党员现任职务",
  partyApplicationDate: "submit.入党申请书落款日期",
  activistDate: "acknowledge.确定积极分子日期",
  developmentTargetDate: "candidate.党委备案日期（确定发展对象日期）",
  branchMeetingApproveProbationaryDate: "wish.支部大会通过预备的日期",
  probationaryInspectionEndDate: "wish.预备党员考察期截止日期",
  inspector1Name: "probationary.入党考察人1",
  inspector1Position: "probationary.入党考察人1职务",
  inspector1FormalMember: "probationary.入党考察人1是否正式党员",
  inspector2Name: "probationary.入党考察人2",
  inspector2Position: "probationary.入党考察人2职务",
  inspector2FormalMember: "probationary.入党考察人2是否正式党员",
  committeeApprovalDate: "wish.党委审批日期",
  oathDate: "probationary.入党宣誓日期",
  oathLocation: "probationary.入党宣誓地点",
  admissionStrengthsWeaknesses: "probationary.入党时主要优缺点",
  basicInfoRemark: "probationary.备注",
  quarters: [
    probationaryQuarter("season2_1", "一"),
    probationaryQuarter("season2_2", "二"),
    probationaryQuarter("season2_3", "三"),
    probationaryQuarter("season2_4", "四"),
  ],
  branchOpinionHalfYear: "season2_half.党支部意见（半年）",
  branchOpinionHalfYearDate: "season2_half.党支部意见（半年）落款日期",
  publicConsultationDate: "formal.群众座谈会日期",
  publicNoticeStartDate: "formal.预备党员转正公示起始日期",
  publicNoticeEndDate: "formal.预备党员转正公示结束日期",
  conversionResolutionDate:
    "formal.支部大会通过预备党员能否转为正式党员的决议落款日期",
  preConversionBranchReviewOpinion:
    "formal.预备党员转正前党支部审查意见（预备党员考察册结束）",
  preConversionBranchReviewOpinionDate:
    "formal.预备党员转正前党支部审查意见落款日期",
});

export const WISH_FIELDS = defineFieldIds({
  name: "basic.姓名",
  gender: "basic.性别",
  ethnicity: "basic.民族",
  birthYearMonth: "basic.出生年月",
  nativePlace: "basic.籍贯",
  birthPlace: "basic.出生地",
  idNumber: "basic.身份证号",
  leagueJoinYearMonth: "basic.入团年月",
  education: "wish.学历",
  degree: "wish.学位或职称",
  unitPosition: "wish.单位、职务或职业",
  residence: "wish.现居住地",
  specialty: "wish.有何专长",
  wishContent: "wish.志愿书电子版内容",
  resume: "wish.本人经历",
  leagueSchool: "wish.加入共青团时所在学校",
  rewardInfo: "wish.何时何地何原因受过何种奖励",
  spouseFlag: "wish.是否有配偶",
  spouseName: "wish.配偶姓名",
  spouseEthnicity: "wish.配偶民族",
  spouseBirthYearMonth: "wish.配偶出生年月",
  spouseNativePlace: "wish.配偶籍贯",
  spouseEducation: "wish.配偶学历",
  spouseWorkStart: "wish.配偶参加工作时间",
  spousePoliticalStatus: "wish.配偶政治面貌",
  spouseUnitPosition: "wish.配偶单位、职务或职业",
  familyMembers: "wish.家庭其他成员",
  introducerOpinion1: "wish.入党介绍人1意见",
  introducerOpinion2: "wish.入党介绍人2意见",
  introducerDate: "wish.入党介绍人意见落款日期",
  branchResolution: "wish.支部大会通过接收申请人为预备党员的决议",
  branchResolutionDate: "wish.支部大会通过预备的日期",
  committeeApprovalDate: "wish.党委审批日期",
  formalResolution:
    "formal.支部大会通过预备党员能否转为正式党员的决议（回到入党志愿书）",
  formalResolutionDate:
    "formal.支部大会通过预备党员能否转为正式党员的决议落款日期",
  formalCommitteeDate: "formal.基层党委审批意见落款日期",
});

export const TEMPLATE_FIELD_IDS = Object.freeze({
  "party-applicant-document": TALK_FIELDS.fieldIds,
  "party-training-inspection-book": Object.freeze([
    ...Object.values(ACTIVIST_FIELDS.person),
    ...Object.values(ACTIVIST_FIELDS.quarters[0]),
    ...Object.values(ACTIVIST_FIELDS.quarters[1]),
    ...Object.values(ACTIVIST_FIELDS.branchHalfYear),
    ...Object.values(ACTIVIST_FIELDS.quarters[2]),
    ...Object.values(ACTIVIST_FIELDS.quarters[3]),
    ...Object.values(ACTIVIST_FIELDS.branchAnnual),
    ...Object.values(ACTIVIST_FIELDS.candidate),
    ACTIVIST_FIELDS.wishBookNumber,
  ]),
  "party-training-inspection-book-v2": Object.freeze([
    PROBATIONARY_FIELDS.personName,
    PROBATIONARY_FIELDS.organizationOrClass,
    PROBATIONARY_FIELDS.probationaryPartyBranch,
    PROBATIONARY_FIELDS.gender,
    PROBATIONARY_FIELDS.birthYearMonth,
    PROBATIONARY_FIELDS.nativePlace,
    PROBATIONARY_FIELDS.educationLevel,
    PROBATIONARY_FIELDS.currentPosition,
    PROBATIONARY_FIELDS.partyApplicationDate,
    PROBATIONARY_FIELDS.activistDate,
    PROBATIONARY_FIELDS.developmentTargetDate,
    PROBATIONARY_FIELDS.branchMeetingApproveProbationaryDate,
    PROBATIONARY_FIELDS.probationaryInspectionEndDate,
    PROBATIONARY_FIELDS.inspector1Name,
    PROBATIONARY_FIELDS.inspector1Position,
    PROBATIONARY_FIELDS.inspector1FormalMember,
    PROBATIONARY_FIELDS.inspector2Name,
    PROBATIONARY_FIELDS.inspector2Position,
    PROBATIONARY_FIELDS.inspector2FormalMember,
    PROBATIONARY_FIELDS.committeeApprovalDate,
    PROBATIONARY_FIELDS.oathDate,
    PROBATIONARY_FIELDS.oathLocation,
    PROBATIONARY_FIELDS.admissionStrengthsWeaknesses,
    PROBATIONARY_FIELDS.basicInfoRemark,
    ...Object.values(PROBATIONARY_FIELDS.quarters[0]),
    ...Object.values(PROBATIONARY_FIELDS.quarters[1]),
    PROBATIONARY_FIELDS.branchOpinionHalfYear,
    PROBATIONARY_FIELDS.branchOpinionHalfYearDate,
    ...Object.values(PROBATIONARY_FIELDS.quarters[2]),
    ...Object.values(PROBATIONARY_FIELDS.quarters[3]),
    PROBATIONARY_FIELDS.publicConsultationDate,
    PROBATIONARY_FIELDS.publicNoticeStartDate,
    PROBATIONARY_FIELDS.publicNoticeEndDate,
    PROBATIONARY_FIELDS.conversionResolutionDate,
    PROBATIONARY_FIELDS.preConversionBranchReviewOpinion,
    PROBATIONARY_FIELDS.preConversionBranchReviewOpinionDate,
  ]),
  "party-application-wish-book": WISH_FIELDS.fieldIds,
});
