export const TEMPLATE_PAGE_CONTRACTS = Object.freeze({
  "party-applicant-document": Object.freeze([
    "cover",
    "registration",
    "interview-record",
    "blank",
  ]),
  "party-training-inspection-book": Object.freeze([
    "cover",
    "instructions",
    "basic-info",
    "quarter-1-2",
    "branch-half-year-opinion",
    "quarter-3-4",
    "branch-annual-opinion",
    "mass-opinion",
    "branch-committee-opinion",
    "deputy-secretary-and-committee-record",
    "training-and-political-review",
    "publicity-and-branch-review",
  ]),
  "party-training-inspection-book-v2": Object.freeze([
    "cover",
    "inside-cover-blank",
    "instructions",
    "basic-info",
    "education-record-quarter-1-2",
    "branch-half-year-opinion",
    "education-record-quarter-3-4",
    "public-consultation",
    "public-notice",
    "pre-conversion-branch-review",
  ]),
  "party-application-wish-book": Object.freeze([
    "cover",
    "instructions",
    "oath",
    "basic-info-and-wish",
    "resume-and-league",
    "awards-politics-spouse",
    "family-and-issue",
    "issue-continuation",
    "introducer-opinions",
    "branch-resolution-and-upper-organization",
    "general-branch-and-committee-approval",
    "formal-conversion-decision",
    "extended-conversion-decision",
    "back-cover",
  ]),
});
